ALTER TABLE gechat_conversation_members
  ADD COLUMN IF NOT EXISTS muted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE gechat_conversations
  ADD COLUMN IF NOT EXISTS only_admins_can_edit BOOLEAN NOT NULL DEFAULT FALSE;
