// Apenas dados (labels + 9 imagens por categoria)
// Fácil de testar, versionar e trocar depois por assets locais (ex: /public/banners/...)
export const BANNER_CATEGORIES = {
  genesis: {
    label: "Gênesis",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/1.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/2.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/3.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/4.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/5.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/6.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/7.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/8.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/genesis/9.jpg",
    ],
  },
  nature: {
    label: "Natureza",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/lago.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/montanha_nuvem.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/nuvem.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/onda.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/pinheiros.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/praia.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/scoty.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/solnascente.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/natureza/windows.jpg",
    ],
  },
  urban: {
    label: "Urbano",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/arranha_ceu.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/aviao.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/city_mar.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/future.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/pink_city.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/rota66.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/simcity.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/skybuild.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/urbano/textura_predio.jpg",
    ],
  },
  cinema: {
    label: "Cinema",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/avengers.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/bb.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/gf.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/got.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/hp1.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/ironman.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/matrix.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/pb.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cinema/sw3_milleniumfalcon.jpg",
    ],
  },
  soccer: {
    label: "Futebol",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/atleticomg.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/bahia.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/botafogo.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/flamengo.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/fluminense.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/gremio.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/pameiras.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/spfc.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/futebol/vasco.jpg",
    ],
  },
  cities: {
    label: "Cidades",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/EAU%20_%20Dubai.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/EGT%20_%20Giza.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/EUA%20_%20Golden%20Gate.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/EUA%20_%20NY%201.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/FR%20_%20Paris%204.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/IND%20_%20Taj%20Mahal.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/JP%20_%20Fuji.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/Prancheta%209.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/cidades/UK%20_%20Londres.jpg",
    ],
  },
  art: {
    label: "Arte",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/Colville.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/Hokussai.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/michelangelo.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/Nam%20June%20Paik.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/Picasso.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/Rembrandt.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/Tarsila.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/Van%20Gogh.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/arte/Dali.jpg",
    ],
  },
  universe: {
    label: "Universo",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/anel_roxo.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/astronauta.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/cometa.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/explosao.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/galaxia.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/pink_sky.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/saturno.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/supernova.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/universo/terra.jpg",
    ],
  },
  abstract: {
    label: "Abstrato",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/apple.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/atriom.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/bola.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/caixas.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/flor.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/onda_roxa.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/pontilhismo.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/queda.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/abstrato/reflexo.jpg",
    ],
  },
  hobbies: {
    label: "Hobbies",
    images: [
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/culinaria.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/fotografia.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/Jiujitsu.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/literatura.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/muaythai.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/Pintura.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/skate.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/violao.jpg",
      "https://qnrpiwdfmzoulnakdmxp.supabase.co/storage/v1/object/public/ProfileBanner/hobbies/Xadrez.jpg",
    ],
  },
};

// Uma ordem única para gerar tabs e iteração:
export const BANNER_ORDER = [
  "genesis",
  "nature",
  "urban",
  "cinema",
  "soccer",
  "cities",
  "art",
  "universe",
  "abstract",
  "hobbies",
];
